### ISSUE TITLE
How to integrate this pod with Storyboard?

### ISSUE THREAD

**Issue by jayvenn** [BenEmdon/CenteredCollectionView#11]
So I have been working around with this pod for a day by now. I wanted the UI really bad for my collection view. I tried giving my collection view on my storyboard the CenteredCollectionView class after pod install but nope. That did not work. If you don't mind sharing how to make this work with  Storyboard, it will make a world of a difference. Thanks.

**Comment by BenEmdon** [comment]
@nhantrivinh rn the CenteredCollectionView doesn't support interface builder (Storyboards and xibs). But I will make interface builder support a high priority for V1.0 release. Stay tuned the next week or so!

**Comment by BenEmdon** [comment]
#19 reactor will integrate storyboard (hopefully without any work)

**Comment by milligator** [comment]
I am also waiting for the storyboard support. I check this repo weekly for the new version.

**Comment by EvanFarrell** [comment]
ZAPIER TEST

**Comment by EvanFarrell** [comment]
Why was my comment deleted? 😠

**Comment by BenEmdon** [comment]
You wrote "ZAPIER TEST"

**Comment by BenEmdon** [comment]
Moved some work off this discussion into #29 
Hopefully someone from the community will pick it up, or I will when I get some time.

**Comment by BenEmdon** [comment]
Storyboard support arrived in version 1.2.2 and I will be adding an integration example in #31.
Next I plan to create an integration guideline. Until then, I will leave this issue open.

**Comment by BenEmdon** [comment]
Just published a storyboard integration tutorial in the [`USAGE.md`](https://github.com/BenEmdon/CenteredCollectionView/blob/master/USAGE.md#storyboard-usage).

An example can be found in the [`Example`](https://github.com/BenEmdon/CenteredCollectionView/tree/master/Example) folder. Open the example project to see more.
