### ISSUE TITLE
didChangeCenteredPage ?

### ISSUE THREAD

**Issue by 16alexanders** [BenEmdon/CenteredCollectionView#16]
Is there anyway to implement a function like didChangeCenteredPage() or something?

I have animations occurring in each of my Collection View Cells but only want the animation to happen when the Cell becomes centered. 

Thanks for your help
-Alex

**Comment by 16alexanders** [comment]
So I found this function you wrote

```
func scrollViewDidEndDecelerating(_ scrollView: UIScrollView) {
		print("Current centered index: \(centeredCollectionView.currentCenteredPage ?? nil)")
        
	}
```
Gonna try to use that to get the currentCenteredPage (which is an Integer) then use that to get the actual cell that is centered using

`let cell = collectionView!.cellForItemAtIndexPath(indexPath)`

and then call a custom animate() function declared in the CollectionViewCell swift file

**Comment by 16alexanders** [comment]
Works!

**Comment by BenEmdon** [comment]
Glad you figured it out!
