### ISSUE TITLE
Swift 4

### ISSUE THREAD

**Issue by smashkins** [BenEmdon/CenteredCollectionView#22]
Could you update for swift 4?
Thanks!

**Comment by BenEmdon** [comment]
Ill be doing a Swift update at some-point when Xcode 9 is out of beta. You're welcome to update it yourself and make a PR, the change should be non trivial.

**Comment by BenEmdon** [comment]
Currently, there is a `swift-4` branch that you can target while I get the release ready (still need to fix CI).

**Comment by BenEmdon** [comment]
Swift 4 compatibility is currently in master and on the latest release.
