### ISSUE TITLE
Storyboard integration example

### ISSUE THREAD

**Issue by BenEmdon** [BenEmdon/CenteredCollectionView#29]
It would nice to have an example to show how to integrate this framework with storyboards. Since storyboards are very popular it would be very beneficial for the future of this project.

I hope to get around to this at some point but am very busy, so if someone in the community could lend a hand it would be greatly appreciated.

**Comment by byroncoetsee** [comment]
Yeah I would love an example of this... I'm trying to figure it out but seriously struggling... 

Most projects are built using Storyboards. Not sure how that wasn't considered from the beginning to be honest 😅 

Will let you know if I figure it out.

**Comment by BenEmdon** [comment]
Hello fellow South African @byroncoetsee  👋 🇿🇦 

When designing this framework I built it in the paradigm that I use (programatically). I hadn't considered the amount of popularity it would receive 🤷‍♂️ moving forwards I plan to make this framework fully support interface builder (but I expect that to be some deal of work). I will likely get to that in a V2 release this summer (northern hemisphere summer 2018). But until then, if you figure out an example of how to get this working in it's current state, I am sure the community will be very appreciative 🙂

**Comment by BenEmdon** [comment]
https://github.com/BenEmdon/CenteredCollectionView/commit/a246265735c9569055785d6fc67ee6f84dd1a19e is a start. This change will prevent crashes for people trying to integrate with storyboards. Next we need to figure out how to make the API `IBInspectable`.

**Comment by BenEmdon** [comment]
Just published a storyboard integration example in the [`USAGE.md`](https://github.com/BenEmdon/CenteredCollectionView/blob/master/USAGE.md#storyboard-usage)
