### ISSUE TITLE
How to scale cells?

### ISSUE THREAD

**Issue by Banck** [BenEmdon/CenteredCollectionView#30]
Hey!
I'm not good at flow layout, please help me with my task.
I need something like that:
![default](https://user-images.githubusercontent.com/6259254/38672475-858f5900-3e78-11e8-8155-ce2961238fbb.jpg)
So I need to scale cells where user scroll the collectionView. How can I do that, through edit your layout?
Thanks!

**Comment by deafjam** [comment]
Hi, you can use this solution. Make different size of cell if it selected. In UICollectionViewCell class make override var isSelected, to make different size of it.

 override var isSelected: Bool { 

        didSet {
            if isSelected {
                UIView.animate(withDuration: 0.2, delay: 0, options: .curveEaseOut, animations: {
                    self.transform = CGAffineTransform(scaleX: 1, y: 1)
                }, completion: nil)
            } else {
                UIView.animate(withDuration: 0.2, delay: 0, options: .curveEaseOut, animations: {
                    self.transform = CGAffineTransform(scaleX: 0.85, y: 0.85)
                }, completion: nil)
            }
        }

**Comment by iamsanketray123** [comment]
@deafjam 
I am not sure, if your solution is correct. @Banck I believe he wanted the cells to scale from 0.85 to 1.0 when they are centered.
