### ISSUE TITLE
Cell not centered

### ISSUE THREAD

**Issue by ChitvanSaxena** [BenEmdon/CenteredCollectionView#33]
**Describe the bug**
The cell is not in center, but if i scroll the collection manuallt, the cell stops at center. Please check image.

**Expected behavior**
Cell should initially appear in center

**Screenshots**

![img_0056](https://user-images.githubusercontent.com/39832760/43401520-02d7acea-942e-11e8-8ff5-3d3f3001b436.png)
![img_0057](https://user-images.githubusercontent.com/39832760/43401532-05205128-942e-11e8-88f1-b1c2af496033.png)

**Comment by BenEmdon** [comment]
Is that power looking button a cell in the CollectionView?

**Comment by ChitvanSaxena** [comment]
No its not, its just a view behind collection view

**Comment by ChitvanSaxena** [comment]
I don't know how but the cells are coming centered now, though I have not changed anything,
but yes, I'll take out time and provide you with a sample project, though I followed the same steps as documented.
Thus closing this thread for now
