### ISSUE TITLE
Convert to Swift 4.2

### ISSUE THREAD

**Issue by swing7wing** [BenEmdon/CenteredCollectionView#34]
When using the pod, Xcode gives a warning that the project isn't Swift 4.2. 
I tested the automatic converter of Xcode, and it looks like everything would still work. 
So probably a very minor change.
<img width="250" alt="screenshot 2018-11-25 at 19 17 17" src="https://user-images.githubusercontent.com/14091307/48982763-242f6e80-f0e7-11e8-8e95-6a651de2d828.png">

**Comment by ethanbonin** [comment]
I did the pod conversion, and it's giving me this error. I've been playing with it for a bit now. I'm not quite sure. Any thoughts? 

<img width="1536" alt="screen shot 2018-11-27 at 9 56 18 am" src="https://user-images.githubusercontent.com/20937454/49093993-e2a7dc00-f22a-11e8-8ba1-07b231395f41.png">

**Comment by ethanbonin** [comment]
I retract my statement. Xcode is just extremely buggy. It works perfectly fine. 👍
I did a clean build (shift+cmd+K) and it said it didn't work, then 5 minutes later, it works.

**Comment by ethanbonin** [comment]
So in order to fix this weird issue. (It seems that it was Xcode). I had to remove the pod and redownload it.

**Comment by swing7wing** [comment]
Awesome progress! And yes Xcode is very buggy, I also had that issue once when converting.
