### ISSUE TITLE
Crash on : collectionView.indexPathForItem(at: currentCenteredPoint)?.row

### ISSUE THREAD

**Issue by SachinPhonepe** [BenEmdon/CenteredCollectionView#37]
collectionView.indexPathForItem(at: currentCenteredPoint)?.row

It's randomly crashing on this line: from crashlytics 

log : 

Fatal Exception: NSInternalInconsistencyException
UICollectionView received layout attributes for a cell with an index path that does not exist: <NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0}

**Comment by BenEmdon** [comment]
Hey, this bug report doesn't provide enough information for me to debug the issue. 
For me to debug this, please respond to the following:
* Can you reproduce this crash on the demo project? 
* Can you provide steps to reproduce this crash?
