### ISSUE TITLE
Is it possible to start the collectionView first cell at the beginning of the list and not centred ?

### ISSUE THREAD

**Issue by AlaeddineOuerteni** [BenEmdon/CenteredCollectionView#43]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Truptika** [comment]
I also have same requirement.

**Comment by AlaeddineOuerteni** [comment]
@Truptika, I created a pull request for this feature.

**Comment by BenEmdon** [comment]
Please reopen this issue after you filled out the details in the body of the issue.
