### ISSUE TITLE
missing step from tutorial

### ISSUE THREAD

**Issue by Coners** [BenEmdon/CenteredCollectionView#44]
<img width="1311" alt="Screenshot 2019-05-15 at 14 57 33" src="https://user-images.githubusercontent.com/49714898/57781488-2ed7d180-7722-11e9-90cb-41e77962d044.png">

**Comment by Coners** [comment]
<img width="974" alt="Screenshot 2019-05-15 at 15 01 06" src="https://user-images.githubusercontent.com/49714898/57781580-66467e00-7722-11e9-8b47-d09c7e4ac526.png">

**Comment by BenEmdon** [comment]
@Coners could you make a pull request to address this? This would make a great open source contribution ✨

**Comment by Coners** [comment]
I could.. trouble is I couldn't get it to work at all and pulled it and just made a View Controller with images in a column.. not ideal.. I was in swift 5 code 10.4 and there were so many red warnings I gave it 4 hours of my life .. two complete installs.. then just binned it :/

**Comment by peterkos** [comment]
I'm fleshing out the provided example that goes into more detail about the `UICollectionViewDelegate` and `UICollectionViewDataSource` protocols. I'll add this change in!

**Comment by BenEmdon** [comment]
This issue was addressed in #48
