### ISSUE TITLE
currentCenteredPage change event

### ISSUE THREAD

**Issue by JorgeFrias** [BenEmdon/CenteredCollectionView#47]
If you use a page control controller to show the user the current page the updating is slow.

To update the controller you have to use one of the methods of `protocol UIScrollViewDelegate`. But they only track events around gestures, which makes the updating slow when they stop scrolling (the earlier event to update is `scrollViewWillBeginDecelerating`, and has a noticeable delay to update)

I think an event for changes over `centeredCollectionViewFlowLayout.currentCenteredPage` would solve the problem.

I tried to use observers but is not possible because is a get only property (I suppose is computed).

It's a similar problem to [#16](https://github.com/BenEmdon/CenteredCollectionView/issues/16), but with "time constraints".

Please tell me if I'm missing something.

*Thanks for such awesome project.*

**Comment by BenEmdon** [comment]
@JorgeFrias if you are able to enhance this, I would be happy to review any code changes you might have. I don’t have the bandwidth to work on this myself.
