### ISSUE TITLE
With Custome Cell we try to add more lable but its not visiable added label

### ISSUE THREAD

**Issue by Mayur5130** [BenEmdon/CenteredCollectionView#51]
I am trying to use this code but if we modified or label add in your sample app then its working but same code we use it and we added custome cell and add more than 3-4 lables in up down area its not display. Only center align lable display.

**Comment by arshadsk5** [comment]
Even same problem occurs for me. Not able to solve

**Comment by BenEmdon** [comment]
Hey @Mayur5130 and@arshadsk5,
I’m sorry you are experiencing an issue. This sounds implementation specific, and it doesn’t sound like it’s the FowLayout’s fault. You haven’t provided enough information either, so I’m going to close this issue.
