### ISSUE TITLE
 First cell not centered before touch (iOS 13)

### ISSUE THREAD

**Issue by dannyalbuquerque** [BenEmdon/CenteredCollectionView#53]
**Describe the bug**
The collection is not vertically centered correctly when the view appears. The collection centers itself once I touch it (slide).

**To Reproduce**
1. Installa Catalina and Xcode Version 11.0 beta 5 
2. Use `pod try CenteredCollectionView`
3. Run project
4. Try programmatic or storyboard examples

**Expected behavior**
Vertically centered collection view

**Screenshots**

Before Slide:
> <img src="https://user-images.githubusercontent.com/11095731/64128770-4052f100-cd86-11e9-858e-201c57f6236f.jpg" height="600">

After slide:
> <img src="https://user-images.githubusercontent.com/11095731/64128805-76907080-cd86-11e9-9961-2343f3a3739c.jpg" height="600">

**Smartphone**
 - Device: iPhone Xs Simulator
 - OS: 13.0
 - Version beta

**Additional context**
This bug only occurs on the beta version of iOS 13. (iPhone Xs Simulator 13.0). Everything is fine with iOS 12.

**Comment by BenEmdon** [comment]
Thank's for this awesome bug report ✨ 
If anyone in the community wants to look into this I would greatly appreciate it 💖

**Comment by dannyalbuquerque** [comment]
Console output on the "Programmatic Example" opening:
```
2019-09-04 08:45:01.995427+0200 CenteredCollectionView_Example[12723:1477393] The behavior of the UICollectionViewFlowLayout is not defined because:
2019-09-04 08:45:01.995588+0200 CenteredCollectionView_Example[12723:1477393] the item height must be less than the height of the UICollectionView minus the section insets top and bottom values, minus the content insets top and bottom values.
2019-09-04 08:45:01.995791+0200 CenteredCollectionView_Example[12723:1477393] The relevant UICollectionViewFlowLayout instance is <CenteredCollectionView.CenteredCollectionViewFlowLayout: 0x7fb01ae17850>, and it is attached to <UICollectionView: 0x7fb01c026400; frame = (0 0; 375 655); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x6000025a23a0>; layer = <CALayer: 0x600002b72ba0>; contentOffset: {-56.333333333333336, -128.66666666666666}; contentSize: {0, 0}; adjustedContentInset: {216.56000000000003, 56.25, 128.56000000000003, 56.25}; layout: <CenteredCollectionView.CenteredCollectionViewFlowLayout: 0x7fb01ae17850>; dataSource: <CenteredCollectionView_Example.ProgrammaticViewController: 0x7fb01ae15be0>>.
2019-09-04 08:45:01.995920+0200 CenteredCollectionView_Example[12723:1477393] Make a symbolic breakpoint at UICollectionViewFlowLayoutBreakForInvalidSizes to catch this in the debugger.
```

**Comment by romain64** [comment]
Still have the same issue

**Comment by hernangonzalez** [comment]
I see it working fine on XCode 11.2, is this still an issue @dannyalbuquerque ?

**Comment by dannyalbuquerque** [comment]
it's working with Xcode Version 11.0 (11A420a)

**Comment by BenEmdon** [comment]
Glad to hear that this one resolved on its own 😅

**Comment by romain64** [comment]
It's not working on Xcode 11.2.1. The cell is not centered horizontally before touch (stuck to the left edge of the screen). This issue first appeared on iOS13.

**Comment by BenEmdon** [comment]
If anyone knows how to fix this then I'll happily review and merge their PR. I'll buy that person some coffee (via a crypto transfer).

**Comment by BenEmdon** [comment]
Haven't been able to reproduce this error. I am going to assume it was a bug in an earlier version of Xcode/iOS. 

Tested on Xcode Version 11.3.1 (11C504)

**Comment by kostapappas** [comment]
@BenEmdon : I solved the issue when I replaced the collectionview width with the screen width. Seems it's a wrong calculation on collection width at the initialization. 

override open func invalidateLayout(with context: UICollectionViewLayoutInvalidationContext) {
        super.invalidateLayout(with: context)
        guard let collectionView = collectionView else { return }
        **let screenSize = UIScreen.main.bounds
        let screenWidth = screenSize.width**
        // invalidate layout to center first and last
        let currentCollectionViewSize = collectionView.bounds.size
        if !currentCollectionViewSize.equalTo(lastCollectionViewSize) || lastScrollDirection != scrollDirection || lastItemSize != itemSize {
            switch scrollDirection {
            case .horizontal:
                let inset = (screenWidth - itemSize.width) / 2
                collectionView.contentInset = UIEdgeInsets(top: 0, left: inset, bottom: 0, right: inset)
                collectionView.contentOffset = CGPoint(x: -inset, y: 0)
            case .vertical:
                let inset = (currentCollectionViewSize.height - itemSize.height) / 2
                collectionView.contentInset = UIEdgeInsets(top: inset, left: 0, bottom: inset, right: 0)
                collectionView.contentOffset = CGPoint(x: 0, y: -inset)
            default:
                collectionView.contentInset = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0)
                collectionView.contentOffset = .zero
            }
            lastCollectionViewSize = currentCollectionViewSize
            lastScrollDirection = scrollDirection
            lastItemSize = itemSize
        }
    }

**Comment by tudi12346** [comment]
still having this issue Xcode 13 minimum target 13
