### ISSUE TITLE
Support iOS 13

### ISSUE THREAD

**Issue by BenEmdon** [BenEmdon/CenteredCollectionView#54]
Right now it appears that CenteredCollectionView doesn't support iOS 13 (ref #53). If anyone in the community of users would like to spare a hand, I would be more than happy to review and merge the code to make CenteredCollectionView support iOS 13.

I'll buy the person that upgrades this some coffee (via a crypto transfer).

I am also looking for a co-maintainer, if anyone is interested 👀

**Comment by Suavatore** [comment]
I'm not seeing any issues with the view not being centred.
Tested on iOS 13.2.2 with Xcode 11.2.1 (iPhone 8 Plus and iPhone 11 Pro Max)
Could it have been a beta bug?

**Comment by BenEmdon** [comment]
Yes it totally could have been a beta bug. @Suavatore how is this cocoapod working for you in iOS 13 so far?

**Comment by Suavatore** [comment]
I didn't use cocoapods, I just downloaded the zip and did some testing (my `pod try` is bugged). If you're asking how the library is working, then its working very well in my experience. Though ultimately I settled on a different library as I needed to scale non-focused cells.

Still, this library is excellent and didn't need any extra work to get it to work properly (unlike the one I'm currently using).

**Comment by BenEmdon** [comment]
Glad it was easy to pick up! What is the library you are mentioning? Maybe CenteredCollectionView is due for some feature work?

**Comment by Suavatore** [comment]
The library I settled on is [UPCarouselFlowLayout](https://github.com/ink-spot/UPCarouselFlowLayout). It unfortunately has a snapping issue, where if you flick the cell, it snaps instantaneously without animating. This [code](https://github.com/ink-spot/UPCarouselFlowLayout/issues/37#issuecomment-411394384) can be used to make it work but it is clearly an ad hoc fix.

I like that you can set the scale and alpha of non-focused cells. These would be good features to add into CenteredCollectionView.

**Comment by BenEmdon** [comment]
Looks like this supports iOS 13.3 fine 👍 Haven't been able to reproduce the bug in #53. If anyone experiences issues please open a new issue and reference this one. Closing and locking 🔒
