### ISSUE TITLE
Support Swift Package Manager

### ISSUE THREAD

**Issue by Dean151** [BenEmdon/CenteredCollectionView#57]
**Is your feature request related to a problem? Please describe.**
Xcode 11 enabled SPM to be used as a dependency manager. Since then, SPM support for libraries would be nice ; especially for One-Class libraries like this one :)

**Describe the solution you'd like**
Create a Package.swift file ; to enable SPM support

**Describe alternatives you've considered**
Cocoapods & Carthage are nice, but they feel heavy for small projects

**Additional context**
If I have spare time in the next few days, I'll submit a tested PR myself ; I could use this nice minimalist lib for a side project I wanna start ;)

**Comment by BenEmdon** [comment]
Hey @dean151, it would be awesome if you could put a PR together for this. I would be happy to review and test it for you.

**Comment by Dean151** [comment]
Here it is. I tested it ; it works ! 😄

**Comment by BenEmdon** [comment]
Hey, this is super awesome 👏 I'll try to test it sometime in my free time this week! You rock @Dean151 🤘
