### ISSUE TITLE
Corner radius is not working in iPhone 6,7,8 and x but it's working fine in xr and plus models

### ISSUE THREAD

**Issue by dharani-123** [BenEmdon/CenteredCollectionView#58]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BenEmdon** [comment]
Please fill out the GitHub issue body for this to be considered. Without any information, we can't debug the problem you are having.
