### ISSUE TITLE
Why is this line needed?

### ISSUE THREAD

**Issue by ahmedk92** [BenEmdon/CenteredCollectionView#64]
https://github.com/BenEmdon/CenteredCollectionView/blob/f2bf371dae314b46f1bc03c222861c9fc40fff32/CenteredCollectionView/Classes/CenteredCollectionViewFlowLayout.swift#L114

Hi, nice library you have there. I've been wondering what is the use of that check here? it seems to be checking if the new offset doesn't lie within the natural bounds, and handle that. But isn't this already solved by the default bouncing behavior? I commented out that check, and the demo worked fine.

**Comment by BenEmdon** [comment]
Thanks! To be honest I don't remember why I added this 😅 I wrote this almost 4 years ago...
When I find some time I'll try to reverse engineer why I added it! 

>  it seems to be checking if the new offset doesn't lie within the natural bounds, and handle that. But isn't this already solved by the default bouncing behavior?

This is a great lead! Thank you. 

If you find removing this works better, please make a PR! Lots of people use this package and it could improve their experience! 😄

**Comment by ahmedk92** [comment]
>If you find removing this works better, please make a PR!

Thank you, I'd love to. But as the saying goes, if it's not broken, don't fix it 😅

So, my plan is to use a fork where this is disabled in my current project. If everything continues to work fine, I'll come back confidently with a PR.

**Comment by BenEmdon** [comment]
It's great that you are battle testing this for us then! 😄 

> If everything continues to work fine, I'll come back confidently with a PR.

That would be amazing. Thank you!
