### ISSUE TITLE
Not able to center the current cell in UITableviewCell. 

### ISSUE THREAD

**Issue by Premal-Khetani** [BenEmdon/CenteredCollectionView#66]
**Describe the bug**
I have used the Collection view in the UITableviewcell. When I reload the cell in uitableview cell. And after reloading the Tableview when i reload the **`centeredCollectionViewFlowLayout.scrollToPage(index: 0, animated: true)`**. It's not working as expected which is cell should be in the center of the screen. 

**Expected behavior**
Should be in the center of the screen. 

**Screenshots**
https://pasteboard.co/JoSCAZC.png

**Desktop (please complete the following information):**
 - OS: iOS

**Smartphone (please complete the following information):**
 - Device: iphone 11 pro
 - OS: ios 13

**Comment by sharukmsd** [comment]
centeredCollectionViewFlowLayout.scrollToPage(index: 0, animated: true) is not scolling to given index in uicollectionview.
